### ISSUE TITLE
Client access restricted with auth module

### ISSUE THREAD

**Issue by jonasberge** [tidal-music/tidal-sdk-web#119]
I executed the following commands:
```
$ git clone https://github.com/tidal-music/tidal-sdk-web tidal-sdk-web-auth-1.3.0
$ cd tidal-sdk-web-auth-1.3.0
$ git checkout auth-1.3.0
$ pnpm --version
9.0.6
$ pnpm install
 WARN  This project is configured to use v8.15.7 of pnpm. Your current pnpm is v9.0.6
...
$ cd packages/auth
$ pnpm install
$ pnpm dev
➜  Local:   http://localhost:5173/
...
```
In another terminal:
```
$ ngrok http 5173
... https://abcd-2001-4dd4-c729-0-e9f1-7ad8-d289-xyz1.ngrok-free.app/ ...
```
I configured a new app in the [developer portal](https://developer.tidal.com/dashboard/), with the following extra settings:
- App Links
  - Application Homepage: https://abcd-2001-4dd4-c729-0-e9f1-7ad8-d289-xyz1.ngrok-free.app
  - Privacy Policy: https://abcd-2001-4dd4-c729-0-e9f1-7ad8-d289-xyz1.ngrok-free.app
- Redirect URLs
  - Redirect URL 1: https://abcd-2001-4dd4-c729-0-e9f1-7ad8-d289-xyz1.ngrok-free.app/examples/login-redirect.html
- Scopes (all enabled)
  - collection.read
  - collection.write
  - playlists.read
  - playlists.write

I opened `https://abcd-2001-4dd4-c729-0-e9f1-7ad8-d289-xyz1.ngrok-free.app/` in a browser. Then I navigated to `/examples/login-redirect.html`. I entered my client ID and the redirect URL that I configured in my app. I was redirected to the login page. I accepted and was redirected to the configured redirect url. Two buttons were shown: "Get user" and "Force Refresh (sub status)". The dev tools contained the following error information:

```
GET https://login.tidal.com/oauth2/me
Status: 400
Body:
{
    "status": 400,
    "error": "unauthorized_client",
    "sub_status": 1002,
    "error_description": "Client access restricted.",
    "errorCodeWrapper": {
        "errorCode": "UNAUTHORIZED_CLIENT"
    }
}
```

Clicking on any of the buttons caused the same error.

The example page says the following:
> You need a properly configured clientId, which is tied to a secure redirect uri.

The latter condition is met. What constitutes as a "properly configured clientId"? It seems mine is not properly configured. Is this still a private API?

I've tried the same thing on the `main` branch, but to no avail, I get the same error message.

The `client-credentials.html` example works just fine.

**Comment by MathiasTim** [comment]
Hello @jonasberge!
Thanks for

**Comment by MathiasTim** [comment]
About the allowed scopes: as you listed above you have access to some scopes in the developer portal, but not all of them.
I think what you have tried with the player tests looks correct, but you are missing the required permissions.

To your question: For now only previews are supported not entire tracks. But we are aware that full-length playback is a requested feature and it is something we are actively looking into.

**Comment by jonasberge** [comment]
Alright, thank you! If there's anything I can help with, I'd be happy to assist.
