### ISSUE TITLE
Is streaming full tracks via tidal-sdk-web supported?

### ISSUE THREAD

**Issue by brentdurksen** [tidal-music/tidal-sdk-web#133]
I'm working on a hobby project of a lightweight, keyboard-driven, text-based UI for streaming music in a browser. TIDAL would be my first choice of streaming service for this project, mostly for its lossless audio formats.

I've been trying to get the `@tidal-music/player` to stream full tracks in high fidelity in a local Vite + Preact app but have encountered the following issues:

1. When I authenticate with the auth code flow using the SDK, the token I receive in return does not have the required scopes to stream music (I see `Token is missing required scope. Required scopes: r_usr playback Actual scopes: ` in the console). However, if I request those scopes, I get a generic error on the OAuth consent screen. The [scopes page](https://developer.tidal.com/documentation/authorization/authorization-scopes) just says "Coming Soon!" for Available Scopes
2. When I authenticate with a client credentials flow (not ideal, as I would like this app to be a fully static/client-side SPA), I can stream a 30-second, low resolution version of the track. This is understandable, since I have authenticated as the application, and not as a premium subscriber.

Is the scenario of streaming full-length tracks in the browser using a token obtained via auth code flow with PKCE supported with the TIDAL web sdk?

**Comment by osmestad** [comment]
Hey, thanks for reaching out. 
For now only playback of 30 second previews are available I'm afraid, but we are investigating full length playback actively.

There has been some threads in our discussion forum on this, like: https://github.com/orgs/tidal-music/discussions/8 so you might find some more information there. 

Hopefully we can allow more uses going forward, but I can't make any promises :-)

**Comment by omstr** [comment]
Man it would be real nice if we could have this

**Comment by lo92fr** [comment]
> Man it would be real nice if we could have remote playback. I've only seen Spotify & Apple Music have it

Any new on the subject, it's now more then one year you said it would be soon available !
