### ISSUE TITLE
Playlist API

### ISSUE THREAD

**Issue by Araxeus** [tidal-music/tidal-sdk-web#161]
https://tidal.com/transfer-music only offers one way of transfering music, a paid third party service...

so i wanted to create a free app that can do the same thing - but there is no official api for interacting with playlists?

how do tunemymusic access playlists? do you have a special monetary deal with them? can I develop a free website that does the same thing?

**Comment by osmestad** [comment]
Hello, this is something we are working on, so I hope we will release it soon (fingers crossed). The discussion section is probably the best place for this, and I assume it will be announced there once ready: https://github.com/orgs/tidal-music/discussions/6
