### ISSUE TITLE
Search results include non existent artist ids

### ISSUE THREAD

**Issue by netlob** [tidal-music/tidal-sdk-web#208]
First of all: thanks for making the API public! Im very enthusiast to add Tidal support to our products :shipit: 

When using the v2 search API I repeatedly get artist ids returned which neither exist in the included field and neither do they exist when calling the explicit /artists/:id endpoint. I tried using different countryCodes but this didnt seem to have any impact on this issue.

How to replicate: 
Search endpoint url: `https://openapi.tidal.com/v2/searchresults/Roxy Dekker?countryCode=NL&include=artists`
Returns
```js
[
  { id: '23893078', type: 'artists' },
  { id: '38420776', type: 'artists' },
  { id: '4637458', type: 'artists' },
  { id: '14562167', type: 'artists' },
  { id: '42684345', type: 'artists' },
  { id: '11103346', type: 'artists' }
]
```

But for example the second result `38420776` doesnt appear anywhere in the included field. When calling the `https://openapi.tidal.com/v2/artists/38420776?countryCode=NL` endpoint it returns a 404:
```json
{
    "errors": [
        {
            "code": "NOT_FOUND",
            "detail": "Artist of a given 'id' 38420776 not found",
            "meta": {
                "category": "INVALID_REQUEST_ERROR"
            }
        }
    ]
}
```

**Comment by aliaksei-taliuk** [comment]
@netlob Hi, thank's for reporting this. Should be fixed now. Please let us know if anything else pops up.
