### ISSUE TITLE
Next track repeats the current song but displays the incorrect title

### ISSUE THREAD

**Issue by c4p741nth** [tidal-music/tidal-sdk-web#212]
When playing a playlist or album on TIDAL, the first track plays normally. However, once the track finishes, the same song repeats, but the displayed title changes to the next track's title. After this bug occurs, the third track plays correctly with the correct title.

Steps to Reproduce:

Start playing a playlist or album.
Let the first track play until the end.
Observe that the first track repeats, but the title displays the next song's title.
After the second track (which repeats the first song), the third track plays correctly with the correct title.
Expected Behavior:
Each track should play in order, and the title should always reflect the currently playing song.

Actual Behavior:
The first track repeats with the title of the second track, and only on the third track does it resume normal behavior.

Environment:

TIDAL Version: [0.5.2] - 2024-10-02
Platform: Web / Application in Desktop

**Comment by enjikaka** [comment]
Hi! Thanks for reporting. Issues using the app should be directed to https://support.tidal.com/hc/en-us

This is already triaged internally and we've got a fix rolling out soon for the app.
