### ISSUE TITLE
Auth requires localStorage, which throws an error in Node

### ISSUE THREAD

**Issue by sir-dunxalot** [tidal-music/tidal-sdk-web#235]
- Expected: `@tidal-music/api` works in Node-based environments
- Actual: `@tidal-music/api` does not work in Node-based environments because it requires @tidal-music/auth, which calls `globalThis.localStorage`
- Suggestions / potential solutions:
  - The library does not change but the documentation states the library works for frontend environments only.
  - `@tidal-music/auth` is updated to support Node environments. It's not realistic to shim `localStorage` in a Node environment because saving to disk is problematic.
  - The developer can use an alternative method for managing credentials. For example, the user could pass their own `getCredentials()` method to `createAPIClient()`:

```ts
const tidalClient = createAPIClient({
  getCredentials: async () => {
    const credentials = await getCredentialsFromDatabase();

    return credentials;
  }
});
```

**Comment by enjikaka** [comment]
Have you tried any in-memory shims for localStorage in Node? Sound like that should work out for you. https://github.com/mnahkies/node-storage-shim
